spring:
  application:
    name: auth-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  cloud:
    aws:
      parameterstore:
        region: eu-central-1
        enabled: true
        endpoint: /auth-service

server:
  port: 8000

logging:
  level:
    org.springframework: INFO

jwt:
  private-key: ${PRIVATE_KEY}
  public-key: ${PUBLIC_KEY}
  access:
    expiration: ${TOKEN_ACCESS_EXPIRATION:300}
  refresh:
    expiration: ${TOKEN_REFRESH_EXPIRATION:10080}